package main.application.states;

public enum FraudRuleType {
    HIGH_AMOUNT,
    RAPID_TRANSACTIONS,
    VELOCITY_BREACH,
    BLACKLISTED_MERCHANT,
    UNUSUAL_LOCATION,
    GRAPH_CIRCULAR_FLOW,
    GRAPH_HIGH_DEGREE_NODE,
    GRAPH_SUSPICIOUS_CLUSTER,
    ANOMALY_SCORE_BREACH,
    CROSS_BORDER_HIGH_RISK
}